name: 'Kafka Action'
description: 'Run Kafka docker conotainer and create a topic'
inputs:
  kafka version:
    description: 'Version of Bitnami Kafka to use'
    required: false
    default: 'latest'
  zookeeper version:
    description: 'Version of Bitnami Zookeeper to use'
    required: false
    default: 'latest'    
  kafka port:
    description: 'The port of Kafka host'
    required: false
    default: 9092
  zookeeper port:
    description: 'The port of Zookeeper host'
    required: false
    default: 2181
  topic name:
    description: 'Topic name to be created'
    required: false
    default: 'mytopic'
runs:
  using: 'docker'
  image: 'Dockerfile'