name: 'Kafka Action'
description: 'Run Kafka docker conotainer and create a topic'
inputs:
  topic_name:
    description: 'topic name to be created'
    required: true
    default: 'topic_name_1'
outputs:
  topic_desc:
    description: 'description of created topic'
runs:
  using: 'docker'
  image: 'Dockerfile'